cryptoshare/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'cryptoshare.views.index', name='index'),
    url(r'^about$', TemplateView.as_view(template_name="about.html")),
    url(r'^contact$', TemplateView.as_view(template_name="contact.html")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^(?P<base_62>.+)$', 'cryptoshare.views.viewmsg', name='encrypted'),

)

cryptoshare/models.py
from django.db import models

import hashlib
from Crypto.Cipher import AES
import os, base64

from cryptoshare.pkcs7 import PKCS7Encoder

class Document(models.Model):
    ciphertext = models.TextField()
    salt = models.CharField(max_length=64)
    created = models.DateTimeField(auto_now_add=True)
    views = models.IntegerField(default=0)

    def encrypt(self, raw, ukey):
        pad = PKCS7Encoder()
        salt = os.urandom(32).encode('base_64')
        key = hashlib.sha256(ukey+salt).digest()
        iv = os.urandom(16)
        msg = pad.encode(raw)
        cipher = AES.new(key, AES.MODE_CBC, iv)
        return (base64.b64encode(iv + cipher.encrypt(msg)), salt)
        

    def decrypt(self, ukey=None):
        unpad = PKCS7Encoder()
        msg = base64.b64decode(self.ciphertext)
        iv = msg[:16]
        key = hashlib.sha256(ukey+self.salt).digest()
        cipher = AES.new(key, AES.MODE_CBC, iv)
        try:
            txt = unpad.decode((cipher.decrypt(msg[16:])))
            self.views += 1
            self.save()
        except:
            txt = "Incorrect Key"
        return txt
        

cryptoshare/forms.py
from django import forms

class RawMessageForm(forms.Form):
    message = forms.CharField(widget=forms.Textarea)
    key = forms.CharField(max_length=256, widget=forms.PasswordInput,
                          label="Encryption Key")
    key2 = forms.CharField(max_length=256, widget=forms.PasswordInput,
                           label="Encryption Key (again)")

    def clean(self):
        key = self.cleaned_data.get('key')
        key2 = self.cleaned_data.get('key2')

        if key and key != key2:
            raise forms.ValidationError("Keys don't match")

        return self.cleaned_data
        
class DecodeForm(forms.Form):
    key = forms.CharField(max_length=256, widget=forms.PasswordInput, label="Key")

cryptoshare/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404

from ratelimit.decorators import ratelimit

from cryptoshare.forms import RawMessageForm, DecodeForm
from cryptoshare.models import Document

import base62_converter

import hashlib
from Crypto.Cipher import AES
import os, binascii, base64

def index(request):
    if request.method == 'POST':
        form = RawMessageForm(request.POST)
        if form.is_valid():
            msg = form.cleaned_data['message']
            key = form.cleaned_data['key']
            doc = Document()
            doc.ciphertext, doc.salt = doc.encrypt(msg, key)
            doc.save()

            url = base62_converter.dehydrate(doc.id)

            return HttpResponseRedirect(reverse('cryptoshare.views.viewmsg',
                                                args=[url]))
    else:
        form = RawMessageForm(None)

    return render(request, 'index.html', {'form': form})

@ratelimit(ip=True, block=True, rate='5/m')
def viewmsg(request, base_62):
    try:
        id = base62_converter.saturate(base_62)
    except:
        return Http404
    doc = get_object_or_404(Document, pk=id)
    plaintext = None
    
    if request.method == 'POST':
        form = DecodeForm(request.POST)
        if form.is_valid():
            key = form.cleaned_data['key']
            plaintext = doc.decrypt(key)
    else:
        form = DecodeForm(None)

    if request.is_ajax():
        return HttpResponse(plaintext)
    else:

        return render(request, 'encrypted.html',
                  {
                      'document': doc,
                      'plaintext': plaintext,
                      'url' : base_62,
                      'form': form,
                  })

templates/about.html
{% extends 'base.html' %}

{% block content  %}
<div id="ww">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <div class="left">
                <h1>About CryptoShare</h1>
                <hr>
                <h3>What is CryptoShare?</h3>
                <p>CryptoShare is a simple message encryption system for sending
                and receiving messages and documents using strong encryption.
                </p>
                <h3>How are messages stored and encrypted?</h3>
                {% include 'cryptomethod.html' %}

                <h3>I lost my key, can you help me?</h3>
                <p>
                Sorry, no. We do not store your key anywhere. If you lost your key, your message is useless (short of <a href="http://en.wikipedia.org/wiki/Brute-force_attack">bruteforcing</a>).
                </p>

                </div><!-- /col-lg-8 -->
        </div><!-- /row -->
    </div> <!-- /container -->
</div><!-- /ww -->
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{{ STATIC_URL }}favicon.ico">

    <title>CryptoShare - The Simple Crypto Message System</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ STATIC_URL }}assets/css/bootstrap.css" rel="stylesheet">


    <!-- Custom styles for this template -->
    <link href="{{ STATIC_URL }}assets/css/main.css" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{{ STATIC_URL }}assets/js/hover.zoom.js"></script>
    <script src="{{ STATIC_URL }}assets/js/hover.zoom.conf.js"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Static navbar -->
    <div class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">CryptoShare</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="about">About</a></li>
            <li><a href="contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

	<!-- +++++ Welcome Section +++++ -->
        {% block content %}

        {% endblock %}
	
	
	<!-- +++++ Footer Section +++++ -->
	
	<div id="footer">
		<div class="container">
			<div class="row">
				<div class="col-lg-4">
					<h4>CryptoShare</h4>
					<p>
                                        http://cryptsh.com<br />
						<a href="https://www.positivessl.com" style="font-family: arial; font-size: 10px; color: #212121; text-decoration: none;"><img src="https://www.positivessl.com/images-new/PositiveSSL_tl_trans2.gif" alt="SSL Certificate" title="SSL Certificate" border="0" /></a>
					</p>
				</div><!-- /col-lg-4 -->
				
				<div class="col-lg-4">
					<h4>Links</h4>
					<p>
						<a href="https://github.com/phrac/cryptoshare">Github Source</a><br/>
					</p>
				</div><!-- /col-lg-4 -->
				
				<div class="col-lg-4">
					<h4>About CryptoShare</h4>
					<p>CryptoShare is a simple encrypted message sharing system.</p>
				</div><!-- /col-lg-4 -->
			
			</div>
		
		</div>
	</div>
	

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{{ STATIC_URL }}assets/js/bootstrap.min.js"></script>
  </body>
</html>

templates/cryptomethod.html
                <p class="text-justify">
                Your message and key are sent to the server via <a
                    href="http://en.wikipedia.org/wiki/Transport_Layer_Security">SSL/TLS</a>. 
                The server then <a href="http://en.wikipedia.org/wiki/Salt_(cryptography)">salts</a> the key and creates a <a href="http://en.wikipedia.org/wiki/Sha256">SHA256</a> hash. Next, the server generates an 
                <a href="http://en.wikipedia.org/wiki/Initialization_vector">initilization vector (IV)</a> from the server's 
                <code><a href="http://en.wikipedia.org/wiki//dev/urandom">/dev/urandom</a></code> device. Your message is then padded to the correct length using a <a href="http://en.wikipedia.org/wiki/PKCS7">PKCS7</a> algorithm. Finally, 
                the server encrypts your message with your salted and hashed key using <a href="http://en.wikipedia.org/wiki/Aes_256">AES 256</a> CBC block mode. 
                After encrypting, the IV is prepended to the encrypted message, <a href="http://en.wikipedia.org/wiki/Base64">base64</a> encoded, 
                and stored in the database along with the salt. <strong>Your key is then discarded.</strong></p>
                
                <p>No identifying information about you or your message is stored. All
                server log messages are sent to <code><a href="http://en.wikipedia.org/wiki//dev/null">/dev/null</a></code>.
                </p>
                
                <p>
                The encryption function is as follows (python):
                </p>
                <pre>
def encrypt(self, raw, ukey):
    pad = PKCS7Encoder()                                # Initialize PKCS7 Encoder
    key = hashlib.sha256(ukey+SALT).digest()            # hash key with SHA256
    iv = os.urandom(16)                                 # Get 16 bytes from urandom
    msg = pad.encode(raw)                               # pad the message (% 16 == 0)
    cipher = AES.new(key, AES.MODE_CBC, iv)             # create an encryption object
    return base64.b64encode(iv + cipher.encrypt(msg))   # encrypt, encode, return
                </pre>

templates/encrypted.html
{% extends 'base.html' %}

{% block content  %}
<div id="ww">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <div class="centered">
                    <h4>This message URL:<h4>
                    <input style="text-align:center" type="text" value="http://cryptsh.com/{{ url }}" />
                </div>

                <h3>Message</h3>

                <pre style="white-space: pre-wrap;" id="plaintext">
{% if plaintext %}
{{ plaintext }}
{% else %}
{{ document.ciphertext }}
{% endif %}
                </pre>
                <form id="decrypt-form" method="post" class="form-inline centered">
                    {% csrf_token %}
                    {% for field in form %}
                    <label for="id_key">{{ field.label }}</label>
                    {{ field }}
                    {% if field.errors %}
                    {% for error in form.key.errors %}
                        <span class="help-block"><strong>{{ error|escape }}</strong></span>
                        {% endfor %}
                    {% endif %}
                    {% endfor %}
                    <button>Decrypt</button>
                </form>

                <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
                <script>
                    $("#decrypt-form").submit(function() {

                        var url = "/{{ url }}"; // the script where you handle the form input.

                        $.ajax({
                            type: "POST",
                            url: url,
                            data: $("#decrypt-form").serialize(),
                            success: function(data)
                            {
                                $('#plaintext').hide().html(data).fadeIn("slow");
                            }
                            return false;
                        });
                    });
                </script>
            </div><!-- /col-lg-8 -->
        </div><!-- /row -->
    </div> <!-- /container -->
</div><!-- /ww -->

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
<div id="ww">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>encrypt and share</h2>
                <p>Use <strong>CryptoShare</strong> to create short messages for a friend in a secure manner. These
                messages are encrypted with your key. For your friend to decrypt them, she will need the URL and the key.</p>
                <hr>
                <form role="form" class="form-horizontal" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        <label class="col-sm-3">{{ field.label }}</label>
                        <div class="col-sm-8">
                            {{ field }}
                            {% if field.errors %}
                            <span class="help-block">
                                {{ field.errors }}
                            </span>
                            {% endif %}
                        </div>
                    </div>
                    {% endfor %}
                    {% if form.non_field_errors %}
                    <div class="col-sm-offset-3 col-sm-8">
                        {{ form.non_field_errors }}
                    </div>
                    {% endif %}
                    <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-8">
                            <button type="submit" class="btn btn-default">Encrypt</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <hr>
                <h4>How are my messages stored and encrypted?</h5>
                {% include 'cryptomethod.html' %}

            </div><!-- /col-lg-8 -->
        </div><!-- /row -->
    </div> <!-- /container -->
</div><!-- /ww -->
{% endblock %}